name: URL Parameter Parsing 🔗

on:
  push:
    branches:
      - 2024_sem2
  pull_request:
    branches:
      - 2024_sem2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
            persist-credentials: false

      - name: Install dependencies
        run: |
          npm install
          npm install jest @testing-library/react-hooks supertest --save-dev

      - name: Run tests 🔧
        run: 
          npm test-url
